########################################################
##               MASTER and BETA BUILD                ##
########################################################
- 
  branches:
    only:
      - master
      - beta
  version: version-placeholder-{build}-{branch}
  cache:
    - packages -> **\packages.config
  configuration: Release 
  environment:
    strong_name_key_secret:
      secure: bcmLk9o07UTrGB+wphBFsGMO49JBy8WGntBdzJECZKk=
  install:
    - git submodule update --init --recursive
    - nuget install secure-file -ExcludeVersion
    - secure-file\tools\secure-file -decrypt sigingkey.snk.enc -secret %strong_name_key_secret%
  before_build:
  - ps: >-
      .\Scripts\NugetRestore.ps1;    
      .\Scripts\AssemblyInfoVersionPatcher.ps1 -assemblyInfoPath  ".\SolutionItems\SharedAssemblyInfo.cs"; 
      .\Scripts\BuildPreamble.ps1   
  build:
    verbosity: minimal  
  after_build:
  - ps: >-
      .\Scripts\NuspecVersionPatcher.ps1 -assembly "ApiClientShared\bin\Release\ApiClientShared.dll" -nuspec "api-client-shared.nuspec";
      nuget pack;    
  artifacts:
    - path: '*.nupkg'
  before_test:
  - ps: >-
      .\Scripts\TestPreamble.ps1
  before_deploy:
  - ps: >-
      .\Scripts\DeployPreamble.ps1
  deploy:
    provider: NuGet
    api_key:
      secure: nMAmtNK63ici4czKXtN/6qJUd45rtgSbo4X1ZnZaHiZrNlIBuw1qDbaxX0yH3T/A
    skip_symbols: true
    artifact: /.*\.nupkg/


########################################################
##                    OTHER BRANCHES                  ##
########################################################

-
  version: version-placeholder-{build}-{branch}
  cache:
    - packages -> **\packages.config
  configuration: Release 
  environment:
    strong_name_key_secret:
      secure: bcmLk9o07UTrGB+wphBFsGMO49JBy8WGntBdzJECZKk=  
  install:
    - nuget install secure-file -ExcludeVersion
    - secure-file\tools\secure-file -decrypt keykey.snk.enc -secret %strong_name_key_secret%
  before_build:
  - ps: >-
      .\Scripts\NugetRestore.ps1;    
      .\Scripts\AssemblyInfoVersionPatcher.ps1 -assemblyInfoPath ".\ApiClientShared\Properties\AssemblyInfo.cs";    
  build:
        verbosity: minimal  
  before_test:
  - ps: >-
      .\Scripts\TestPreamble.ps1